<template>
<router-view v-slot="{ Component }">
  <transition name="slide-in-right">
    <component :is="Component" />
  </transition>
</router-view>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

.slide-in-right-enter-active {
	animation: slide-in-right .35s cubic-bezier(0, .33, 0.66, 1) both;
}

.slide-in-left-leave-active {
	animation: slide-in-right .35s cubic-bezier(0, .33, 0.66, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-4-17 16:17:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@keyframes slide-in-right {
  0% {
    transform: translateX(200px);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    opacity: 1;
  }
}
</style>